### ISSUE TITLE
Post time not reported properly

### ISSUE THREAD

**Issue by rmontagnin** [desmos-labs/mooncake#57]
## Generic information
- OS name and version: Both
- Application build code: N.A.
- Network type (mobile/Wi-Fi): Both

## Bug description
Inside a single post item, the posting time does not appear correct. After a minute that a post has been created, the text displays "A couple of hours ago". This is due to the fact that the time is considered to be in UTC instead of the local user time zone. 

## Steps to reproduce
1. Create a post
2. Wait a few minutes
3. Look at the posting time

## Expected behavior
The posting time should be appropriately displayed based on the current timezone of the user, not UTC.

**Comment by rmontagnin** [comment]
This appears to be already fixed with build code `4018`

**Comment by kwunyeung** [comment]
This still happens.

The time on `Mooncake`
![IMG_5093](https://user-images.githubusercontent.com/932636/87333367-992b1280-c56f-11ea-9a37-c169cbe0e326.jpg)

vs the time on `Big Dipper`

![image](https://user-images.githubusercontent.com/932636/87333467-b9f36800-c56f-11ea-9896-070533a228fb.png)

This is the transaction

https://morpheus.desmos.network/transactions/C14C755A4ECD6723C2E1F45E452C152C72559DE14220157C51B0EF434E615BA0
